mode: balance #模式 balance(均衡模式)、parallel(平行模式)
containers: #容器，可配置多个
  - address: http://127.0.0.1:5700 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
    username: zengmin #用户名
    password: zengmin #密码
    weigth: 10 #权重 balance模式下权重越高分得的ck越多，默认1
    mode: #单独对容器进行模式设置
    limit: 50 #限制容器ck数目
#   - address: http://8.142.64.192:5800 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
#     username: zengmin #用户名
#     password: zengmin #密码
#     weigth: 9 #权重 balance模式下权重越高分得的ck越多，默认1
#     mode: #单独对容器进行模式设置
#     limit: 50 #限制容器ck数目
  #- path: /Users/cdle/Desktop/jd_study/xdd/config.sh #本地配置文件路径 v1v2v3v4v5和不知名容器的配置
  # - path: /Users/cdle/Desktop/jd_study/jdc/list.sh
theme: /root/xdd/theme/summer.html #自定义主题，支持本地、网络路径
static: ./static #静态文件 便于自定义二维码页面时，引入css、js等文件
master: jd_653397cf8b316 #管理员账户pin，有多个用'&'拼接
#数据库 支持sqlite3、mysql和postgres
#sqlite3 填路径，默认 ./.xdd
#mysql填 user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
#postgres填 host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
database: /root/xdd/.xdd.db #这个写.xdd.db的绝对路径
qywx_key:  #企业微信推送key
daily_push: #定时任务
resident: jd_653397cf8b316 #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。
master: jd_653397cf8b316 #管理员账号
#自定义ua
user_agent:
telegram_bot_token: #telegram bot token
telegram_user_id: #telegrame user id
qquid: 2460623828 #用于管理的QQ号，扫码用你要做机器人的QQ扫非此QQ
qqgid: 1083397494 #监听的群
default_priority: #新用户默认优先级
no_ghproxy: true #更新资源是否不使用代理 默认false
qbot_public_mode: true  #qq机器人群聊模式，默认私聊模式
daily_asset_push_cron: 58 10 * * * #日常资产推送时间